### ISSUE TITLE
typo in styler customization post

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/lorenzwalthert.github.io#10]
@lorenzwalthert I could not find the source of your current website (maybe private) so posting this here: in https://lorenzwalthert.netlify.app/post/customizing-styler-the-quick-way/ (super useful, thank you!) "using a consistent style (no matter which) reduces fraction in the community." should be "using a consistent style (no matter which) reduces friction in the community." I think.

**Comment by lorenzwalthert** [comment]
thanks, will update. :D
